Better response for invalid avro message
allegro/hermes pull request #1280
Opened 2020-10-10 21:06 UTC by jewertow

## Background context
When clients publish message that does not match the schema they receive response: `Invalid message: Failed to convert JSON to Avro`. Such a message is useless when schema is large. Then users have to ask maintainers to check logs.

## Changes
I want to return response that explains what's wrong with a published message, e.g.:
`Invalid message: Failed to convert JSON to Avro: Field <name> is expected to be type: <type>`.
In the simplest implementation it would be enough to catch the exception `AvroConversionException` thrown by `JsonConverter`, get its cause, append it to the response message and throw new exception. 
But this approach has a performance footprint so we shouldn't do it that way, therefore I suggest to add better message to `JsonConverter` in the `json-avro-converter` and upgrade its version after a release.
I already created a [pull request with this change](https://github.com/allegro/json-avro-converter/pull/55).

For now I added the jar with snapshot version of json-avro-converter and a test to prove the concept.

2020-10-26 12:37 UTC, mareckmareck approved these changes

2020-10-26 12:38 UTC, mareckmareck requested changes

2020-10-26 12:38 UTC, mareckmareck commented on hermes-common/build.gradle
> +    compile files('./json-avro-converter-0.2.10-SNAPSHOT.jar')
I'm fine with that change, remember to change this one after new version is released

2020-11-02 11:18 UTC, druminski submitted a review, later dismissed

2021-02-05 12:07 UTC, druminski approved these changes

2021-02-08 12:42 UTC, piotrrzysko approved these changes

2021-02-08 12:43 UTC, merged