Add option to skip events in hermes console
allegro/hermes pull request #1579
Opened 2022-10-14 07:21 UTC by sobelek

2022-10-19 06:42 UTC, pitagoras3 requested changes
Hi @sobelek, thank you for your contribution!

I ran your PR locally, and I modified it a little bit. Here are my suggestions:
1. Merge `Retransmit` and `Skip messages` actions into one bootstrap panel. I highly suggest using [list groups](https://getbootstrap.com/docs/3.3/components/#panels-list-group).
2. Change color of the panel from `panel-danger` to `panel-default`.
3. Add tooltips showing action description when you hover the mouse over tooltip.
4. Move panel with retransmission and skipping messages to the left side (to make width of both sides more equal).

Final result could look like this:
![Screenshot 2022-10-19 at 08 28 55](https://user-images.githubusercontent.com/16356036/196615781-17364196-17bf-4135-9109-124f2709ffdb.png)

If you have any questions regarding implementation of those propositions, don't hesitate to ask questions :)

2022-10-24 09:31 UTC, pitagoras3 commented
Hi @sobelek,

> Do you think we should get rid of this information in modal and instead show it in tooltip? Or maybe this information should be shown in both places?

I think that this info should be shown in both places, to make sure that we inform the user what he/she is doing :)

2022-10-25 16:41 UTC, sobelek commented
@pitagoras3 
Done :) Screenshot from current version:
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/39651555/197832967-b8f87a86-1c2c-4dbf-b57d-07bfc7dd0836.png">

2022-10-27 07:55 UTC, pitagoras3 approved these changes

2022-10-27 08:18 UTC, piotrrzysko approved these changes

2022-10-27 08:42 UTC, merged