Propagating http headers in Kafka headers
allegro/hermes pull request #1612
Opened 2022-10-31 18:08 UTC by druminski

2022-11-17 15:01 UTC, moscicky requested changes

2022-11-17 15:01 UTC, moscicky commented on hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/config/KafkaHeaderNameProperties.java
> +    private Set<String> internalHeaders = Set.of(messageId, timestamp, schemaId, schemaVersion);
`Set#of` creates an immutable collection so updating in `updateInternalHeaders` will throw an `UnsupportedOperationException`.  

We should switch to mutable set here or remove `updateInternalHaders` at all and implement `isNotInternal` as:

```java
public boolean isNotInternal(String name) {
        return Set.of(this.messageId, this.timestamp, this.schemaId, this.schemaVersion).contains(name);
    }
```

2022-11-17 15:09 UTC, moscicky commented on hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/config/KafkaHeaderNameProperties.java
> +    private Set<String> internalHeaders = Set.of(messageId, timestamp, schemaId, schemaVersion);
also: the fact that it didn't blow up in integration tests mean that tests for this part are missing

2022-11-17 15:16 UTC, moscicky commented on hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/config/KafkaHeaderNameProperties.java
>      private String timestamp = "ts";
shouldn't this be removed?

2022-11-17 15:17 UTC, moscicky commented on hermes-frontend/src/main/java/pl/allegro/tech/hermes/frontend/producer/kafka/KafkaHeaderFactory.java
> +
shouldn't we remove `timestamp` from this class?

2022-12-09 07:38 UTC, moscicky commented on hermes-consumers/src/main/java/pl/allegro/tech/hermes/consumers/config/KafkaHeaderNameProperties.java
> +    private Set<String> internalHeaders = Set.of(messageId, timestamp, schemaId, schemaVersion);
I agree that writing tests just for this class is not necessary. What I meant is that we have a piece of configuration that is never used is integration tests, so we never check if everything is wired correctly by spring and that properties are applied correctly. If we don't test all properties in e2e tests that we can only find out about bugs after deployment

2022-12-09 07:51 UTC, moscicky approved these changes

2023-03-10 08:44 UTC, piotrrzysko commented
> Name of the Kafka header is the same as the HTTP header name.

2023-03-10 09:09 UTC, piotrrzysko commented
> Name of the Kafka header is the same as the HTTP header name. 

I'm not sure if this is OK. If I'm not mistaken, it opens up the possibility of overwriting internal headers from outside of Hermes. I'd suggest at least giving higher priority to the internal headers or prefixing the external ones.  

Also, I'm wondering about hiding this feature behind a flag. Currently, if someone doesn't want to migrate to this mechanism, they will still have to incur costs of storing additional data in Kafka.

2023-10-19 12:33 UTC, druminski commented
> > Name of the Kafka header is the same as the HTTP header name.
> 
> I'm not sure if this is OK. If I'm not mistaken, it opens up the possibility of overwriting internal headers from outside of Hermes. I'd suggest at least giving higher priority to the internal headers or prefixing the external ones.
> 
> Also, I'm wondering about hiding this feature behind a flag. Currently, if someone doesn't want to migrate to this mechanism, they will still have to incur costs of storing additional data in Kafka.

@piotrrzysko I took into account your comment and:
1. introduced prefix for Kafka headers propagating HTTP headers
2. introduced flag which can enable/disable this propagation mechanism. True is its default value.
3. updated PR description
4. please take a look at the changes

2023-10-19 13:36 UTC, faderskd approved these changes

2023-10-25 14:48 UTC, piotrrzysko approved these changes

2023-11-03 12:29 UTC, merged