New subscription form
allegro/hermes pull request #1719
Opened 2023-09-04 11:22 UTC by szczygiel-m

2023-09-14 09:09 UTC, moscicky requested changes
Great work, this PR required a significant effort to prepare :) I have left some suggestions but overall - congrats

2023-09-14 09:09 UTC, moscicky commented on hermes-console-vue/src/composables/subscription/use-form-subscription/useFormSubscription.ts
> +export function initializeFulfilledForm(
suggestion: `Fulfilled` is not the right word to use in this context. Use `FullyFilled` instead

2023-09-14 09:09 UTC, moscicky commented on hermes-console-vue/src/composables/subscription/use-create-subscription/useCreateSubscription.ts
> +  watch(
this piece of code is the same as in `editSubscription`, maybe we should have some helper functions for searching the owners?

2023-09-14 14:32 UTC, szczygiel-m commented on hermes-console-vue/src/views/subscription/subscription-form/SubscriptionForm.vue
> +  function importFormData() {
When we are importing form from file we are creating new subscription and we want to be sure, that we are using computed value from dataSources (as You can see, source can be deprecated and it is filtered there, not to let creating subscription with deprecated ownerSource). But when we are editing subscription, I assume it is better to get ownerSources from appconfig, to let user change something even when ownerSource is deprecated, but it is just my assumption.

2023-09-14 14:36 UTC, szczygiel-m commented on hermes-console-vue/src/views/subscription/subscription-form/SubscriptionForm.vue
> +      notificationStore.dispatchNotification({
The problem is with emitting an event from composable, it is possible [link](https://stackoverflow.com/questions/72394953/how-to-fire-an-emit-event-from-vue-composable) but it require s an additional setup and can be tricky. Also we are not using `useFormSubscription` in this component for now

2023-09-14 14:39 UTC, szczygiel-m commented on hermes-console-vue/src/views/subscription/subscription-form/SubscriptionForm.vue
> +      v-if="isSerialDeliveryTypeSelected"
thats correct, current form also works like that

2023-09-14 14:50 UTC, szczygiel-m commented on hermes-console-vue/src/views/subscription/subscription-form/SubscriptionForm.vue
> +        $t('subscriptionForm.fields.monitoringReaction.placeholder')
I just cut the text, because i wasn't able to find an option for placeholder wrapping :/

2023-09-15 08:02 UTC, moscicky approved these changes

2023-09-15 08:10 UTC, merged